# Generated by Django 4.2.1 on 2023-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="school",
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="buyers location"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default=1,
                max_length=15,
                unique=True,
                verbose_name="Phone number of user",
            ),
            preserve_default=False,
        ),
    ]
