# Generated by Django 4.2.1 on 2023-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id of the food",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, verbose_name="the name of the food"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="price of the food")),
                (
                    "available",
                    models.BooleanField(
                        default=False,
                        verbose_name="determines if the food is available or not",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Say whatever you want about the food",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=100,
                        verbose_name="select category where food belongs",
                    ),
                ),
                ("image", models.ImageField(upload_to="image/", verbose_name="image")),
            ],
        ),
    ]
