# Generated by Django 4.2.1 on 2023-07-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_food_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        max_length=256,
                        verbose_name="the email of the user wanting to buy",
                    ),
                ),
                (
                    "total_price",
                    models.IntegerField(
                        blank=True, verbose_name="total price of the food"
                    ),
                ),
                (
                    "ordered_items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_food_items",
                        to="restaurant.food",
                    ),
                ),
            ],
        ),
    ]
