# Generated by Django 4.2.1 on 2023-07-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_reservation_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="type",
            field=models.CharField(
                default=1,
                max_length=256,
                verbose_name="type of meal: food, drink, pasteries",
            ),
            preserve_default=False,
        ),
    ]
