# Generated by Django 4.2.1 on 2023-07-15 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0004_rename_user_email_userorder_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorder",
            name="ordered_items",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_food_items",
                to="restaurant.food",
            ),
        ),
        migrations.AlterField(
            model_name="userorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
